services:
  app-cpu: &base
    build:
      context: .
      dockerfile: Dockerfile
    image: cf-graph-ml-image:dev
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      - HF_TOKEN=${HF_TOKEN:-}

  app-rocm:
    <<: *base
    build:
      context: .
      dockerfile: Dockerfile.rocm
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    security_opt:
      - seccomp=unconfined

  app-cuda:
    <<: *base
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility